import { type ReactNode } from 'react'
import { type Metadata } from 'next'
import { Toaster } from '@/components/ui/sonner'
import { ReactQueryProvider } from '@/components/react-query-provider'
import { SolanaProvider } from '@/components/solana-provider'
import { Header } from '@/components/header'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'YETO',
  description: 'Generated by create next app'
}

export default function RootLayout({ children, modal }: Readonly<{ children: ReactNode; modal: ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <body className="text-dark bg-white antialiased dark:bg-black dark:text-white">
        <ReactQueryProvider>
          <SolanaProvider>
            <Header />
            {modal}
            {children}
            <Toaster />
          </SolanaProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
